import = [
"~/.config/alacritty/tokyo-night.toml"
#"~/.config/alacritty/monokai.toml"
#"~/.config/alacritty/midnight-haze.toml"
]

[font]
size = 12

[font.normal]
family = "Source Code Pro"

[window]
opacity = 0.9
decorations = "buttonless"
dynamic_padding = false

[window.padding]
x = 15
y = 15

# spawn new instance
[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]
