
[font]
size = 14

[font.normal]
family = "Source Code Pro"

[window]
# title="Alacritty"
# startup_mode="Fullscreen"
# opacity = 0.9
# decorations = "buttonless"
# decorations = "Full"
# dynamic_padding = false
# blur = true

[selection]
save_to_clipboard=true

[cursor]

[window.padding]
x = 0
y = 0

# dh spawn new instance in current folter with CTRL+SHIFT+RETURN
[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]

[general]

live_config_reload=true
import = [
	"~/.config/alacritty/tokyo-night.toml"
	#"~/.config/alacritty/monokai.toml"
	#"~/.config/alacritty/midnight-haze.toml"
]
